import type { Event } from '@/types';

export const events: Event[] = [
  {
    id: '1',
    name: 'Tech Innovators Summit',
    date: new Date('2024-10-15T09:00:00'),
    location: 'Grand Auditorium',
    description: 'A gathering of the brightest minds in technology and innovation. Keynotes, panels, and networking opportunities.',
    category: 'Tech',
    image: 'https://placehold.co/400x600/1e3a8a/ffffff.png',
    aiHint: 'tech conference',
  },
  {
    id: '2',
    name: 'Annual Music Fest',
    date: new Date('2024-10-20T14:00:00'),
    location: 'Campus Green',
    description: 'An outdoor music festival featuring local bands and student performers. Food trucks and fun for everyone.',
    category: 'Music',
    image: 'https://placehold.co/400x600/c026d3/ffffff.png',
    aiHint: 'music festival',
  },
  {
    id: '3',
    name: 'Startup Pitch Night',
    date: new Date('2024-11-05T18:00:00'),
    location: 'Innovation Hub',
    description: 'Watch as student entrepreneurs pitch their business ideas to a panel of venture capitalists.',
    category: 'Career',
    image: 'https://placehold.co/400x600/f97316/ffffff.png',
    aiHint: 'startup pitch',
  },
  {
    id: '4',
    name: 'Abstract Art Exhibition',
    date: new Date('2024-11-12T10:00:00'),
    location: 'Fine Arts Gallery',
    description: 'Explore a curated collection of abstract art from renowned and emerging artists.',
    category: 'Art',
    image: 'https://placehold.co/400x600/8b5cf6/ffffff.png',
    aiHint: 'art gallery',
  },
  {
    id: '5',
    name: 'Championship Basketball Game',
    date: new Date('2024-11-18T19:00:00'),
    location: 'University Arena',
    description: 'Cheer on the home team as they compete for the championship title. Go Tigers!',
    category: 'Sports',
    image: 'https://placehold.co/400x600/dc2626/ffffff.png',
    aiHint: 'basketball game',
  },
  {
    id: '6',
    name: 'Career Fair 2024',
    date: new Date('2024-11-22T11:00:00'),
    location: 'Exhibition Hall',
    description: 'Connect with top employers from various industries. Bring your resume and dress to impress.',
    category: 'Career',
    image: 'https://placehold.co/400x600/16a34a/ffffff.png',
    aiHint: 'job fair',
  },
   {
    id: '7',
    name: 'AI in Practice Workshop',
    date: new Date('2024-12-02T13:00:00'),
    location: 'Computer Science Bldg, Rm 101',
    description: 'A hands-on workshop on implementing machine learning models for real-world applications.',
    category: 'Tech',
    image: 'https://placehold.co/400x600/3b82f6/ffffff.png',
    aiHint: 'ai workshop',
  },
  {
    id: '8',
    name: 'Winter Jazz Concert',
    date: new Date('2024-12-10T20:00:00'),
    location: 'Performing Arts Center',
    description: 'An evening of smooth jazz performed by the university\'s award-winning jazz ensemble.',
    category: 'Music',
    image: 'https://placehold.co/400x600/6d28d9/ffffff.png',
    aiHint: 'jazz concert',
  },
];
